name-template: "v$RESOLVED_VERSION ğŸš€"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "âš ï¸ Breaking Changes"
    labels:
      - "breaking"
      - "major"
  - title: "ğŸš€ Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "ğŸ› Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "ğŸ§° Maintenance"
    labels:
      - "chore"
      - "maintenance"
  - title: "ğŸ“š Documentation"
    labels:
      - "documentation"
  - title: "â¬†ï¸ Dependencies"
    collapse-after: 5
    labels:
      - "dependencies"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - "major"
      - "breaking"
  minor:
    labels:
      - "minor"
      - "feature"
  patch:
    labels:
      - "patch"
      - "fix"
      - "bugfix"
      - "bug"
  default: patch

sort-by: "merged_at"
sort-direction: "descending"

exclude-labels:
  - "skip-changelog"

autolabeler:
  - label: "documentation"
    files:
      - "*.md"
  - label: "bug"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
  - label: "feature"
    branch:
      - '/feature\/.+/'
  - label: "dependencies"
    files:
      - "yarn.lock"

template: |
  ## Changes in Release v$RESOLVED_VERSION
  $CHANGES
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION